package:
  name: snapwrap
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - scikit-image
    - pyyaml
    - panel >=1.7.0
    - sqlalchemy >=2.0.0

test:
  imports:
    - snapwrap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neutrons/SNAPWrap/
  license: MIT
  summary: Instrument Scientist Scripting Interface into SNAPRed
  description: |
    SNAPWrap provides a scripting interface for instrument scientists
    to interact with the SNAPRed data reduction package.
  dev_url: https://github.com/neutrons/SNAPWrap/
  doc_url: https://github.com/neutrons/SNAPWrap/

extra:
  recipe-maintainers:
    - neutrons
