isLite: true
SEE:
  home: /SNS/SNAP/shared/SEEMeta
  json: 
    home: ${SEE.home}/jsons
    components: ${SEE.json.home}/components
    cylinderCells: ${SEE.json.home}/cylinderCells
    opposedAnvilCells: ${SEE.json.home}/opposedAnvilCells
  materials:
    database: ${SEE.home}/materials/materials.db
    spectra: ${SEE.home}/materials/spectra
cleanTree: true
