#!/bin/bash
#Edited version of Yuanpeng's original script for NOMAD confirmation
#
# 7/Feb/2022 now calls slightly modified version of confirm-data that allows an empty string
# to be specified for reduction type (relevant when reduction has not been performed).
#
# original script: /SNS/software/nses/bin/confirm-data
# new script: /SNS/SNAP/shared/devel/confirm-data

echo ""
echo "++++++++++++++++++++++++++++++++"
echo "+ SNAP reduction confirmation +"
echo "++++++++++++++++++++++++++++++++"
echo ""

if [ "$#" = 0 ] ; then
    echo -n "IPTS To Confirm? -> "
    read ipts
    
    echo ""
    echo "--------------------------------"
    echo "0 -> No"
    echo "1 -> Yes"
    echo "2 -> Partially"
    echo "3 -> Unknown"
    echo "4 -> None Expected"
    echo "--------------------------------"
    echo -n "Reduced Data Availability? -> "
    read ipts_status
    
    echo ""
    echo "--------------------------------"
    echo "0 -> Auto Reduction"
    echo "1 -> With Scripts"
    echo "2 -> By CIS"
    echo "3 -> <<leave blank>>"
    echo "--------------------------------"
    echo -n "Reduction Type? -> "
    read reduction_type
    
    echo ""
    echo -n "Submission Number? (This is the number after decimal point in ipts. If not sure, press [Enter]) -> "
    read submission_num
    if [ "$submission_num" = "" ] ; then
        submission_num="1"
    fi
    
    echo ""
    echo "--------------------------------"
    echo "0 -> "
    echo "1 -> Non-standard experiment, bespoke reduction scripts developed by LC/CIS"
    echo "2 -> Experiment unsuccessful due to sample/technical issues"
    echo "3 -> Manual set-up required"
    echo "4 -> SNAPRed/1 snapwrap
    echo "--------------------------------"
    echo -n "Which comment? (If no comments, press [Enter]) -> "
    read comment_num
    
    ipts_status_list=( "No" "Yes" "Partially" "Unknown" "None Expected")
    reduction_type_list_out=("Auto Reduction" "With Scripts" "By CIS" "")
    reduction_type_list_use=("Auto" "Scripts" "CIS" "_")
    reduction_comment=("" "Non-standard experiment, bespoke reduction scripts developed by LC/CIS" "Experiment unsuccessful due to sample/technical issues" "Manual set-up required" "SNAPRed/snapwrap")
    echo ""
    echo "++++++++++++++++++++++++++++++++++++++++"
    echo "+             Info Summary             +"
    echo "++++++++++++++++++++++++++++++++++++++++"
    echo ""
    echo "Instrument        : SNAP"
    echo "IPTS To Confirm   : $ipts"
    echo "Reduced Data Availability : ${ipts_status_list[$ipts_status]}"
    echo "Reduction Type    : ${reduction_type_list_out[$reduction_type]}"
    echo "Submission Number : ${submission_num}"
    echo "Comments          : ${reduction_comment[$comment_num]}"
    echo ""
    echo "++++++++++++++++++++++++++++++++++++++++"
    echo ""
    echo -n "All look good? ([Y/y]N/n) -> "
    read go_ahead
    if [ "$go_ahead" = "" ] ; then
        go_ahead="Y"
    fi
    
    while [ "$go_ahead" != "Y" ] && [ "$go_ahead" != "y" ] && [ "$go_ahead" != "N" ] && [ "$go_ahead" != "n" ]
    do
        echo -n "All look good? ([Y/y]N/n) -> "
        read go_ahead
        if [ "$go_ahead" = "" ] ; then
            go_ahead="Y"
        fi
    done
    
    if [ "$go_ahead" = "Y" ] || [ "$go_ahead" = "y" ] ; then
        echo ""
        echo "Submitting IPTS confirmation to database..."
    #    if [ "$comments" != "" ] ; then
        if [ "${reduction_comment[$comment_num]}" != "" ] ; then
             /SNS/SNAP/shared/Malcolm/devel/confirm-data SNAP $ipts ${submission_num} \
                ${reduction_type_list_use[$reduction_type]} \
                -c "${reduction_comment[$comment_num]}" -s ${ipts_status_list[$ipts_status]}

            
        else 
            /SNS/SNAP/shared/Malcolm/devel/confirm-data SNAP $ipts ${submission_num} \
                ${reduction_type_list_use[$reduction_type]} \
                -s ${ipts_status_list[$ipts_status]}	
        fi
        echo ""
        echo "Success!"
        echo ""
    else
        echo "Exiting..."
    fi
# Set defaults below here    
elif [ "$#" = 1 ] ; then
    ipts=$1
    echo "Submitting IPTS confirmation to database..."
    /SNS/SNAP/shared/Malcolm/devel/confirm-data SNAP $ipts 1 Scripts -c "No comment" -s Yes
    echo ""
    echo "Success!"
    echo ""
    echo "-----------------------------"
    echo "           Summary          "
    echo "-----------------------------"
    echo "Instrument        : SNAP"
    echo "IPTS              : $ipts"
    echo "Reduction Type    : With Scripts"
    echo "Reduced Data Availability : Yes"
    echo "Submission Number : 1"
    echo "-----------------------------"
    echo ""
elif [ "$#" = 2 ] ; then
    ipts=$1
    sub_num=$2
    echo "Submitting IPTS confirmation to database..."
    /SNS/SNAP/shared/Malcolm/devel/confirm-data SNAP $ipts $sub_num Scripts -c "No comment" -s Yes
    echo ""
    echo "Success!"
    echo ""
    echo "-----------------------------"
    echo "           Summary          "
    echo "-----------------------------"
    echo "Instrument        : SNAP"
    echo "IPTS              : $ipts"
    echo "Reduction Type    : With Scripts"
    echo "Reduced Data Availability : Yes"
    echo "Submission Number : $sub_num"
    echo "-----------------------------"
    echo ""
else
    echo ""
    echo "----------------------------------------------"
    echo "Usage-1: confirm-SNAP                          "
    echo "Usage-2: confirm-SNAP IPTS                     "
    echo "Usage-3: confirm-SNAP IPTS Submission_Number   "
    echo "----------------------------------------------"
    echo ""
fi
