"""Setup panel for the Campaign Manager.

Phase 4a: Assets table with Ingest button.
Phase 4b: Pixel mask registration form.
Phase 4c (pending): Crystal phase builder.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from qtpy.QtCore import QAbstractTableModel, QModelIndex, Qt, Signal  # type: ignore
from qtpy.QtWidgets import (  # type: ignore
    QCheckBox,
    QComboBox,
    QFileDialog,
    QFormLayout,
    QFrame,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QPlainTextEdit,
    QPushButton,
    QScrollArea,
    QStackedWidget,
    QTableView,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

_ASSET_COLUMNS = ["Asset ID", "Type", "Scope", "Status"]

# Artefact-type combo indices
_TYPE_PIXEL_MASK = 0
_TYPE_CRYSTAL_PHASE = 1
_TYPE_BIN_MASK_MONITOR = 2
_TYPE_BIN_MASK_MANUAL = 3
_TYPE_BIN_MASK_WORKSPACE = 4
_TYPE_BIN_MASK_JSON = 5


# ── Assets table ──────────────────────────────────────────────────────────────

class _AssetTableModel(QAbstractTableModel):
    def __init__(self, rows: list[dict[str, Any]], parent=None) -> None:
        super().__init__(parent)
        self._rows = rows

    def setRows(self, rows: list[dict[str, Any]]) -> None:
        self.beginResetModel()
        self._rows = rows
        self.endResetModel()

    def rowCount(self, parent: QModelIndex = QModelIndex()) -> int:  # noqa: B008
        return 0 if parent.isValid() else len(self._rows)

    def columnCount(self, parent: QModelIndex = QModelIndex()) -> int:  # noqa: B008
        return 0 if parent.isValid() else len(_ASSET_COLUMNS)

    def headerData(self, section: int, orientation: Qt.Orientation, role: int = Qt.DisplayRole) -> Any:
        if role == Qt.DisplayRole and orientation == Qt.Horizontal:
            return _ASSET_COLUMNS[section]
        return None

    def data(self, index: QModelIndex, role: int = Qt.DisplayRole) -> Any:
        if not index.isValid() or role != Qt.DisplayRole:
            return None
        row = self._rows[index.row()]
        col = index.column()
        if col == 0:
            return row.get("asset_id", "")
        if col == 1:
            return row.get("asset_type", "")
        if col == 2:
            app = row.get("applicability") or {}
            scope = app.get("scope", "campaign")
            rn = app.get("run_number")
            return f"run {rn}" if scope == "run" and rn is not None else "campaign"
        if col == 3:
            return row.get("status", "")
        return None


# ── Pixel mask form ───────────────────────────────────────────────────────────

class _PixelMaskForm(QWidget):
    """Inline form for registering a pixel mask artefact.

    The artefact ID is auto-generated by the model from the method, source
    stem, and lite/native tag — the operator does not need to invent one.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QFormLayout(self)
        layout.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        # isLite toggle (default True)
        self._liteCheck = QCheckBox("Lite mode")
        self._liteCheck.setChecked(True)
        self._liteCheck.setToolTip(
            "Lite (18 432-pixel) and native (1 179 648-pixel) masks are "
            "incompatible — ensure this matches your reduction mode."
        )
        layout.addRow("Instrument mode:", self._liteCheck)

        # Method
        self._methodCombo = QComboBox()
        self._methodCombo.addItem("Standard PE (letterbox)", userData="pixel_mask.letterbox")
        self._methodCombo.addItem("Custom .nxs file", userData="pixel_mask.custom")
        self._methodCombo.addItem("ADS workspace", userData="pixel_mask.workspace")
        self._methodCombo.currentIndexChanged.connect(self._onMethodChanged)
        layout.addRow("Source:", self._methodCombo)

        # File path (custom only)
        self._fileRow = QWidget()
        file_layout = QHBoxLayout(self._fileRow)
        file_layout.setContentsMargins(0, 0, 0, 0)
        self._fileEdit = QLineEdit()
        self._fileEdit.setPlaceholderText("Path to .nxs pixel mask file")
        file_layout.addWidget(self._fileEdit)
        browse_btn = QPushButton("Browse…")
        browse_btn.clicked.connect(self._onBrowse)
        file_layout.addWidget(browse_btn)
        self._fileLabel = QLabel("File:")
        layout.addRow(self._fileLabel, self._fileRow)
        self._fileLabel.setVisible(False)
        self._fileRow.setVisible(False)

        # ADS workspace picker
        self._wsPickRow = QWidget()
        ws_pick_layout = QHBoxLayout(self._wsPickRow)
        ws_pick_layout.setContentsMargins(0, 0, 0, 0)
        self._wsPickCombo = QComboBox()
        self._wsPickCombo.setMinimumWidth(220)
        ws_pick_layout.addWidget(self._wsPickCombo, stretch=1)
        refresh_btn = QPushButton("Refresh")
        refresh_btn.setToolTip("Reload workspace list from the Mantid ADS")
        refresh_btn.clicked.connect(self._refreshWorkspaces)
        ws_pick_layout.addWidget(refresh_btn)
        self._wsPickLabel = QLabel("Workspace:")
        layout.addRow(self._wsPickLabel, self._wsPickRow)
        self._wsPickLabel.setVisible(False)
        self._wsPickRow.setVisible(False)

        # Mantid workspace name (used during reduction to load the mask)
        self._wsNameEdit = QLineEdit()
        self._wsNameEdit.setText("pixmask_pe")
        self._wsNameEdit.setPlaceholderText("Mantid workspace name for reduction")
        layout.addRow("Workspace name:", self._wsNameEdit)

        # Run number (optional)
        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        layout.addRow("Run number:", self._runEdit)

        # Notes
        self._notesEdit = QPlainTextEdit()
        self._notesEdit.setPlaceholderText("Optional notes")
        self._notesEdit.setFixedHeight(55)
        layout.addRow("Notes:", self._notesEdit)

        # Seed the workspace list on construction
        self._refreshWorkspaces()

    def _onBrowse(self) -> None:
        path, _ = QFileDialog.getOpenFileName(
            self, "Select pixel mask file", "", "Nexus files (*.nxs);;All files (*)"
        )
        if path:
            self._fileEdit.setText(path)

    def _refreshWorkspaces(self) -> None:
        """Populate the ADS workspace combo from the Mantid ADS."""
        self._wsPickCombo.clear()
        try:
            from mantid.api import AnalysisDataService as ADS  # type: ignore
            names = sorted(ADS.getObjectNames())
        except Exception:
            names = []
        for name in names:
            self._wsPickCombo.addItem(name)
        if not names:
            self._wsPickCombo.addItem("(no workspaces in ADS)")

    def _onMethodChanged(self, _index: int) -> None:
        method = self._methodCombo.currentData()
        is_custom = method == "pixel_mask.custom"
        is_workspace = method == "pixel_mask.workspace"
        is_letterbox = method == "pixel_mask.letterbox"

        self._fileLabel.setVisible(is_custom)
        self._fileRow.setVisible(is_custom)
        self._wsPickLabel.setVisible(is_workspace)
        self._wsPickRow.setVisible(is_workspace)

        # PE letterbox mask is lite — lock the toggle to reflect that
        if is_letterbox:
            self._liteCheck.setChecked(True)
            self._liteCheck.setEnabled(False)
            self._wsNameEdit.setText("pixmask_pe")
        else:
            self._liteCheck.setEnabled(True)
            self._wsNameEdit.setText(
                "pixmask_ws" if is_workspace else "pixmask_custom"
            )

    def params(self) -> dict[str, Any]:
        method = self._methodCombo.currentData()
        run_text = self._runEdit.text().strip()
        try:
            run_number: int | None = int(run_text) if run_text else None
        except ValueError:
            run_number = None
        p: dict[str, Any] = {
            "method": method,
            "is_lite": self._liteCheck.isChecked(),
            "ws_name": self._wsNameEdit.text().strip(),
            "run_number": run_number,
            "notes": self._notesEdit.toPlainText().strip() or None,
        }
        if method == "pixel_mask.custom":
            p["nxs_path"] = self._fileEdit.text().strip()
        elif method == "pixel_mask.workspace":
            p["ads_workspace"] = self._wsPickCombo.currentText()
        return p

    def validate(self) -> str | None:
        """Return an error message, or None if the form is valid."""
        p = self.params()
        if not p["ws_name"]:
            return "Workspace name is required."
        if p["method"] == "pixel_mask.custom" and not p.get("nxs_path"):
            return "A .nxs file path is required for the custom method."
        if p["method"] == "pixel_mask.workspace" and p.get("ads_workspace", "").startswith("("):
            return "Select a workspace from the ADS list."
        return None


# ── EOS sub-form ──────────────────────────────────────────────────────────────

_V0_UNIT_CELL = "Å³/unit cell"
_V0_UNIT_ATOM = "Å³/atom"
_V0_UNIT_MOL  = "cm³/mol"

# 1 cm³/mol → Å³ per formula unit (Z=1):  1e24 Å³ / 6.02214076e23
_CM3_MOL_TO_A3 = 1e24 / 6.02214076e23  # ≈ 1.66054


class _EosSubForm(QGroupBox):
    """Optional checkable EOS group for _CrystalPhaseForm.

    Unchecked by default (EOS is optional).  When checked the operator
    provides EOS type, V₀ (with unit conversion), K₀, K', a mandatory
    literature reference, and optional stability bounds.
    """

    def __init__(self, parent=None) -> None:
        super().__init__("Equation of state", parent)
        self.setCheckable(True)
        self.setChecked(False)
        self.setToolTip("Tick to provide EOS parameters for pressure work.")

        outer = QVBoxLayout(self)
        outer.setContentsMargins(4, 4, 4, 4)

        # All form content lives in this widget, shown/hidden by the checkbox.
        self._content = QWidget()
        outer.addWidget(self._content)
        self._content.setVisible(False)
        self.toggled.connect(self._onToggled)

        layout = QFormLayout(self._content)
        layout.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        # EOS type
        self._typeCombo = QComboBox()
        self._typeCombo.addItem("Birch-Murnaghan", userData="birch-murnaghan")
        self._typeCombo.addItem("Vinet", userData="vinet")
        self._typeCombo.addItem("Murnaghan", userData="murnaghan")
        layout.addRow("EOS type:", self._typeCombo)

        # V₀ with unit selector
        v0_row = QWidget()
        v0_layout = QHBoxLayout(v0_row)
        v0_layout.setContentsMargins(0, 0, 0, 0)
        self._v0Edit = QLineEdit()
        self._v0Edit.setPlaceholderText("e.g. 15.862")
        v0_layout.addWidget(self._v0Edit, stretch=2)
        self._v0UnitCombo = QComboBox()
        self._v0UnitCombo.addItem(_V0_UNIT_CELL)
        self._v0UnitCombo.addItem(_V0_UNIT_ATOM)
        self._v0UnitCombo.addItem(_V0_UNIT_MOL)
        self._v0UnitCombo.currentIndexChanged.connect(self._onUnitChanged)
        v0_layout.addWidget(self._v0UnitCombo, stretch=1)
        layout.addRow("V₀:", v0_row)

        # Z — shown only when unit requires conversion
        self._zLabel = QLabel("Z (formula units/cell):")
        self._zEdit = QLineEdit()
        self._zEdit.setPlaceholderText("positive integer, e.g. 2")
        self._zEdit.setToolTip(
            "Number of formula units per unit cell.\n"
            "Required to convert from per-atom or per-mol units."
        )
        layout.addRow(self._zLabel, self._zEdit)
        self._zLabel.setVisible(False)
        self._zEdit.setVisible(False)

        # K₀
        self._k0Edit = QLineEdit()
        self._k0Edit.setPlaceholderText("bulk modulus in GPa, e.g. 295.2")
        layout.addRow("K₀ (GPa):", self._k0Edit)

        # K'
        self._kpEdit = QLineEdit()
        self._kpEdit.setPlaceholderText("pressure derivative, e.g. 4.32")
        layout.addRow("K′ (dimensionless):", self._kpEdit)

        # Reference (mandatory when EOS enabled)
        self._sourceEdit = QLineEdit()
        self._sourceEdit.setPlaceholderText(
            "e.g. Dewaele et al., PRB 70 094112 (2004)"
        )
        layout.addRow("Reference (required):", self._sourceEdit)

        # Stability bounds header
        stab_label = QLabel(
            "<i>Approximate stability bounds for your experimental conditions</i> (all optional):"
        )
        stab_label.setWordWrap(True)
        layout.addRow(stab_label)

        # Pressure bounds
        p_row = QWidget()
        p_layout = QHBoxLayout(p_row)
        p_layout.setContentsMargins(0, 0, 0, 0)
        self._pMinEdit = QLineEdit()
        self._pMinEdit.setPlaceholderText("P_min")
        self._pMaxEdit = QLineEdit()
        self._pMaxEdit.setPlaceholderText("P_max")
        p_layout.addWidget(QLabel("P_min:"))
        p_layout.addWidget(self._pMinEdit)
        p_layout.addSpacing(8)
        p_layout.addWidget(QLabel("P_max:"))
        p_layout.addWidget(self._pMaxEdit)
        layout.addRow("Pressure (GPa):", p_row)

        # Temperature bounds
        t_row = QWidget()
        t_layout = QHBoxLayout(t_row)
        t_layout.setContentsMargins(0, 0, 0, 0)
        self._tMinEdit = QLineEdit()
        self._tMinEdit.setPlaceholderText("T_min")
        self._tMaxEdit = QLineEdit()
        self._tMaxEdit.setPlaceholderText("T_max")
        t_layout.addWidget(QLabel("T_min:"))
        t_layout.addWidget(self._tMinEdit)
        t_layout.addSpacing(8)
        t_layout.addWidget(QLabel("T_max:"))
        t_layout.addWidget(self._tMaxEdit)
        layout.addRow("Temperature (K):", t_row)

    def _onToggled(self, checked: bool) -> None:
        self._content.setVisible(checked)
        # setVisible alone doesn't propagate a layout-request through
        # QStackedWidget — walk up and re-activate every layout so the
        # parent chain re-allocates space correctly.
        p = self.parentWidget()
        while p is not None:
            if p.layout() is not None:
                p.layout().invalidate()
                p.layout().activate()
            p = p.parentWidget()

    def _onUnitChanged(self, _index: int) -> None:
        needs_z = self._v0UnitCombo.currentText() != _V0_UNIT_CELL
        self._zLabel.setVisible(needs_z)
        self._zEdit.setVisible(needs_z)

    @staticmethod
    def _opt_float(edit: QLineEdit) -> float | None:
        t = edit.text().strip()
        if not t:
            return None
        try:
            return float(t)
        except ValueError:
            return None

    def _v0_in_cell_units(self) -> float | None:
        v0 = self._opt_float(self._v0Edit)
        if v0 is None:
            return None
        unit = self._v0UnitCombo.currentText()
        if unit == _V0_UNIT_CELL:
            return v0
        try:
            z = int(self._zEdit.text().strip())
        except ValueError:
            return None
        if z <= 0:
            return None
        if unit == _V0_UNIT_ATOM:
            return v0 * z
        return v0 * z * _CM3_MOL_TO_A3  # cm³/mol

    def params(self) -> dict[str, Any] | None:
        """Return EOS params dict, or None if the group is unchecked."""
        if not self.isChecked():
            return None
        p_min = self._opt_float(self._pMinEdit)
        p_max = self._opt_float(self._pMaxEdit)
        t_min = self._opt_float(self._tMinEdit)
        t_max = self._opt_float(self._tMaxEdit)
        return {
            "eos_type": self._typeCombo.currentData(),
            "V_0": self._v0_in_cell_units(),
            "K_0": self._opt_float(self._k0Edit),
            "K_prime": self._opt_float(self._kpEdit),
            "source": self._sourceEdit.text().strip(),
            "stability_pressure": [p_min, p_max] if (p_min is not None or p_max is not None) else None,
            "stability_temperature": [t_min, t_max] if (t_min is not None or t_max is not None) else None,
        }

    def validate(self) -> str | None:
        if not self.isChecked():
            return None
        v0_raw = self._opt_float(self._v0Edit)
        if v0_raw is None:
            return "V₀ is required."
        if v0_raw <= 0:
            return "V₀ must be positive."
        if self._v0UnitCombo.currentText() != _V0_UNIT_CELL:
            try:
                z = int(self._zEdit.text().strip())
                if z <= 0:
                    raise ValueError
            except ValueError:
                return "Z (formula units/cell) must be a positive integer for the selected unit."
        k0 = self._opt_float(self._k0Edit)
        if k0 is None:
            return "K₀ is required."
        if k0 <= 0:
            return "K₀ must be positive (GPa)."
        if self._opt_float(self._kpEdit) is None:
            return "K′ is required."
        if not self._sourceEdit.text().strip():
            return "A literature reference is required for the EOS."
        return None


# ── Bin mask from transmission monitor form ───────────────────────────────────

class _BinMaskFromMonitorForm(QWidget):
    """Form for building a bin mask from the transmission monitor spectrum.

    Runs ``build_swiss_cheese_from_transmission_monitor`` (Mantid required)
    to auto-detect notch positions, then registers the result.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QFormLayout(self)
        layout.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("e.g. 65923")
        layout.addRow("Run number:", self._runEdit)

        # Wavelength bounds — optional; leave blank to auto-detect from
        # instrument state via SNAPRed.
        lam_row = QWidget()
        lam_layout = QHBoxLayout(lam_row)
        lam_layout.setContentsMargins(0, 0, 0, 0)
        self._lamMinEdit = QLineEdit()
        self._lamMinEdit.setPlaceholderText("auto")
        self._lamMaxEdit = QLineEdit()
        self._lamMaxEdit.setPlaceholderText("auto")
        lam_layout.addWidget(QLabel("min:"))
        lam_layout.addWidget(self._lamMinEdit)
        lam_layout.addSpacing(8)
        lam_layout.addWidget(QLabel("max:"))
        lam_layout.addWidget(self._lamMaxEdit)
        lam_layout.addWidget(QLabel("Å"))
        layout.addRow("Wavelength range:", lam_row)
        layout.labelForField(lam_row).setToolTip(
            "Leave blank to auto-detect from the instrument state."
        )

        self._dipEdit = QLineEdit()
        self._dipEdit.setText("0.98")
        self._dipEdit.setToolTip(
            "Fraction of the continuum below which a dip is flagged as a notch. "
            "Lower values find more (shallower) notches."
        )
        layout.addRow("Dip threshold:", self._dipEdit)

        self._keepDiagCheck = QCheckBox("Retain diagnostic workspaces")
        self._keepDiagCheck.setChecked(True)
        self._keepDiagCheck.setToolTip(
            "Keep intermediate workspaces (monitor, rebinned, ratio, SNIP continuum) "
            "in the Mantid ADS so you can inspect the notch detection result. "
            "Disable once the detection parameters are tuned."
        )
        layout.addRow("Diagnostics:", self._keepDiagCheck)

        self._l2OverrideCheck = QCheckBox("Override default monitor position")
        self._l2OverrideCheck.setChecked(False)
        self._l2OverrideCheck.setToolTip(
            "Normally not needed. Enable when the monitor L2 value embedded "
            "in the NeXus file is incorrect (e.g. missing calibration)."
        )
        layout.addRow("Monitor L2:", self._l2OverrideCheck)

        self._l2Edit = QLineEdit()
        self._l2Edit.setPlaceholderText("e.g. 4.910")
        self._l2Edit.setToolTip("Monitor 2 flight-path length (m) to use instead of the NeXus value.")
        self._l2Edit.setEnabled(False)
        layout.addRow("L2 (m):", self._l2Edit)

        self._l2OverrideCheck.toggled.connect(self._l2Edit.setEnabled)

    @staticmethod
    def _opt_float(edit: QLineEdit) -> float | None:
        t = edit.text().strip()
        return float(t) if t else None

    def params(self) -> dict[str, Any]:
        try:
            run_number: int | None = int(self._runEdit.text().strip())
        except ValueError:
            run_number = None
        try:
            dip = float(self._dipEdit.text().strip())
        except ValueError:
            dip = 0.98
        return {
            "run_number": run_number,
            "lam_min": self._opt_float(self._lamMinEdit),
            "lam_max": self._opt_float(self._lamMaxEdit),
            "dip_threshold": dip,
            "keep_diagnostics": self._keepDiagCheck.isChecked(),
            "monitor2_l2": self._opt_float(self._l2Edit) if self._l2OverrideCheck.isChecked() else None,
        }

    def validate(self) -> str | None:
        p = self.params()
        if p["run_number"] is None:
            return "A valid run number is required."
        lam_min = p["lam_min"]
        lam_max = p["lam_max"]
        if (lam_min is not None) != (lam_max is not None):
            return "Provide both wavelength bounds or leave both blank."
        if lam_min is not None and lam_max is not None and lam_min >= lam_max:
            return "Wavelength min must be less than max."
        dip = p["dip_threshold"]
        if not (0 < dip < 1):
            return "Dip threshold must be between 0 and 1."
        if self._l2OverrideCheck.isChecked():
            l2 = self._opt_float(self._l2Edit)
            if l2 is None or l2 <= 0:
                return "Monitor L2 override requires a positive value in metres."
        return None


# ── Bin mask from manual notch list form ──────────────────────────────────────

class _BinMaskManualForm(QWidget):
    """Form for building a bin mask from a manually entered list of notches.

    The operator enters (min, max) pairs directly.  No Mantid is required
    to build the mask — ``notchFromList`` only constructs the JSON.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        form = QFormLayout()
        form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
        layout.addLayout(form)

        # Units
        self._unitsCombo = QComboBox()
        self._unitsCombo.addItem("Wavelength (Å)", userData="Wavelength")
        self._unitsCombo.addItem("d-spacing (Å)", userData="dSpacing")
        form.addRow("Units:", self._unitsCombo)

        # Lite / native toggle
        self._liteCheck = QCheckBox("Lite mode")
        self._liteCheck.setChecked(True)
        self._liteCheck.setToolTip(
            "Lite (18 432-pixel) and native (1 179 648-pixel) masks are "
            "incompatible — match this to your reduction mode."
        )
        form.addRow("Instrument mode:", self._liteCheck)

        # Run number (optional)
        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        form.addRow("Run number:", self._runEdit)

        # Notch table
        tbl_label = QLabel("Notches:")
        tbl_label.setAlignment(Qt.AlignRight | Qt.AlignTop)
        tbl_container = QWidget()
        tbl_layout = QVBoxLayout(tbl_container)
        tbl_layout.setContentsMargins(0, 0, 0, 0)

        self._table = QTableWidget(0, 2)
        self._table.setHorizontalHeaderLabels(["Min", "Max"])
        self._table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self._table.verticalHeader().setVisible(False)
        self._table.setSelectionBehavior(QTableWidget.SelectRows)
        self._table.setSelectionMode(QTableWidget.SingleSelection)
        self._table.setFixedHeight(160)
        tbl_layout.addWidget(self._table)

        btn_row = QHBoxLayout()
        add_btn = QPushButton("Add notch")
        add_btn.clicked.connect(self._onAdd)
        remove_btn = QPushButton("Remove selected")
        remove_btn.clicked.connect(self._onRemove)
        btn_row.addWidget(add_btn)
        btn_row.addWidget(remove_btn)
        btn_row.addStretch(1)
        tbl_layout.addLayout(btn_row)

        form.addRow(tbl_label, tbl_container)

        # Notes
        self._notesEdit = QPlainTextEdit()
        self._notesEdit.setPlaceholderText("Optional notes")
        self._notesEdit.setFixedHeight(55)
        form.addRow("Notes:", self._notesEdit)

        # Seed with one empty row so the operator sees the table immediately
        self._onAdd()

    # ── Slots ──────────────────────────────────────────────────────────

    def _onAdd(self) -> None:
        r = self._table.rowCount()
        self._table.insertRow(r)
        self._table.setItem(r, 0, QTableWidgetItem(""))
        self._table.setItem(r, 1, QTableWidgetItem(""))
        self._table.editItem(self._table.item(r, 0))

    def _onRemove(self) -> None:
        rows = sorted(
            {idx.row() for idx in self._table.selectedIndexes()}, reverse=True
        )
        for r in rows:
            self._table.removeRow(r)

    # ── Public API ─────────────────────────────────────────────────────

    def _parseNotches(self) -> list[list[float]]:
        notches: list[list[float]] = []
        for r in range(self._table.rowCount()):
            min_item = self._table.item(r, 0)
            max_item = self._table.item(r, 1)
            try:
                lo = float(min_item.text().strip() if min_item else "")
                hi = float(max_item.text().strip() if max_item else "")
                notches.append([lo, hi])
            except ValueError:
                pass
        return notches

    def params(self) -> dict[str, Any]:
        run_text = self._runEdit.text().strip()
        try:
            run_number: int | None = int(run_text) if run_text else None
        except ValueError:
            run_number = None
        return {
            "notches": self._parseNotches(),
            "units": self._unitsCombo.currentData(),
            "is_lite": self._liteCheck.isChecked(),
            "run_number": run_number,
            "notes": self._notesEdit.toPlainText().strip() or None,
        }

    def validate(self) -> str | None:
        notches = self._parseNotches()
        if not notches:
            return "Enter at least one notch (Min / Max pair)."
        for i, (lo, hi) in enumerate(notches, start=1):
            if lo <= 0 or hi <= 0:
                return f"Notch {i}: both values must be positive."
            if lo >= hi:
                return f"Notch {i}: Min must be less than Max."
        # Check for overlaps
        sorted_n = sorted(notches, key=lambda n: n[0])
        for i in range(len(sorted_n) - 1):
            if sorted_n[i][1] > sorted_n[i + 1][0]:
                return (
                    f"Notches overlap: [{sorted_n[i][0]}, {sorted_n[i][1]}] and "
                    f"[{sorted_n[i+1][0]}, {sorted_n[i+1][1]}]. "
                    "Merge or separate them."
                )
        return None


# ── Bin mask from workspace history form ─────────────────────────────────────


class _BinMaskFromWorkspaceForm(QWidget):
    """Form for building a bin mask from a workspace's MaskBins algorithm history.

    The operator applies masks in Mantid's Instrument View and then points this
    form at the resulting workspace.  ``extractFromWorkspaceHistory`` scans the
    algorithm history for ``MaskBins`` calls and reconstructs the notch list.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        form = QFormLayout()
        form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
        layout.addLayout(form)

        self._wsEdit = QLineEdit()
        self._wsEdit.setPlaceholderText("ADS workspace name — must have MaskBins in history")
        self._wsEdit.setToolTip(
            "Name of the workspace in the Mantid Analysis Data Service.\n"
            "Apply masks via Instrument View → Draw → Mask first, then enter\n"
            "the workspace name here.  The MaskBins algorithm history is\n"
            "extracted automatically."
        )
        form.addRow("Workspace:", self._wsEdit)

        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        form.addRow("Run number:", self._runEdit)

        self._notesEdit = QPlainTextEdit()
        self._notesEdit.setPlaceholderText("Optional notes")
        self._notesEdit.setFixedHeight(55)
        form.addRow("Notes:", self._notesEdit)

    def params(self) -> dict[str, Any]:
        run_text = self._runEdit.text().strip()
        try:
            run_number: int | None = int(run_text) if run_text else None
        except ValueError:
            run_number = None
        return {
            "ws_name": self._wsEdit.text().strip(),
            "run_number": run_number,
            "notes": self._notesEdit.toPlainText().strip() or None,
        }

    def validate(self) -> str | None:
        if not self._wsEdit.text().strip():
            return "Workspace name is required."
        run_text = self._runEdit.text().strip()
        if run_text:
            try:
                n = int(run_text)
                if n <= 0:
                    return "Run number must be a positive integer."
            except ValueError:
                return f"'{run_text}' is not a valid run number."
        return None


# ── Bin mask from JSON file form ──────────────────────────────────────────────


class _BinMaskFromJsonForm(QWidget):
    """Form for registering a bin mask from a swiss-cheese JSON file on disk.

    Use this when you already have a JSON produced by ``swissCheese.save()``
    and want to bring it into the campaign artefact store.  The file is
    validated via ``swissCheese.load()``, copied into the artefact directory,
    and ``swissCheese.makeMaskBinsTables()`` is called to leave the
    ``maskBins_*`` table workspaces in the ADS ready for use.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        form = QFormLayout()
        form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)
        layout.addLayout(form)

        file_row = QHBoxLayout()
        self._fileEdit = QLineEdit()
        self._fileEdit.setPlaceholderText("Path to swiss-cheese JSON file")
        self._fileEdit.setToolTip(
            "JSON file saved by swissCheese.save() — loaded and validated\n"
            "before registration.  The file is copied into the campaign\n"
            "artefact directory."
        )
        file_row.addWidget(self._fileEdit)
        browse_btn = QPushButton("Browse…")
        browse_btn.setFixedWidth(70)
        browse_btn.clicked.connect(self._onBrowse)
        file_row.addWidget(browse_btn)
        form.addRow("JSON file:", file_row)

        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        form.addRow("Run number:", self._runEdit)

        self._notesEdit = QPlainTextEdit()
        self._notesEdit.setPlaceholderText("Optional notes")
        self._notesEdit.setFixedHeight(55)
        form.addRow("Notes:", self._notesEdit)

    def setDefaultDir(self, directory: str | None) -> None:
        """Set the directory the file browser opens in by default."""
        self._defaultDir = directory or ""

    def _onBrowse(self) -> None:
        start_dir = getattr(self, "_defaultDir", "")
        path, _ = QFileDialog.getOpenFileName(
            self, "Select swiss-cheese JSON", start_dir, "JSON files (*.json)"
        )
        if path:
            self._fileEdit.setText(path)

    def params(self) -> dict[str, Any]:
        run_text = self._runEdit.text().strip()
        try:
            run_number: int | None = int(run_text) if run_text else None
        except ValueError:
            run_number = None
        return {
            "json_path": self._fileEdit.text().strip(),
            "run_number": run_number,
            "notes": self._notesEdit.toPlainText().strip() or None,
        }

    def validate(self) -> str | None:
        if not self._fileEdit.text().strip():
            return "Select a JSON file."
        from pathlib import Path as _Path
        if not _Path(self._fileEdit.text().strip()).exists():
            return f"File not found: {self._fileEdit.text().strip()}"
        run_text = self._runEdit.text().strip()
        if run_text:
            try:
                n = int(run_text)
                if n <= 0:
                    return "Run number must be a positive integer."
            except ValueError:
                return f"'{run_text}' is not a valid run number."
        return None


# ── CIF preview helper ────────────────────────────────────────────────────────

def _cif_preview_text(path: str) -> str:
    """Return a tooltip-friendly crystal summary extracted from a CIF file.

    Uses simple regex extraction — no Mantid required.  Returns an empty
    string if the file cannot be read or parsed.
    """
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    def _get(*keys: str) -> str:
        for key in keys:
            m = re.search(
                rf"^{re.escape(key)}\s+['\"]?([^'\"\n]+)['\"]?",
                text,
                re.MULTILINE | re.IGNORECASE,
            )
            if m:
                return m.group(1).strip()
        return "?"

    sg = _get(
        "_symmetry_space_group_name_H-M",
        "_space_group_name_H-M_alt",
        "_symmetry_space_group_name_h-m",
    )
    formula = _get(
        "_chemical_formula_sum",
        "_chemical_name_mineral",
        "_chemical_formula_structural",
    )
    a = _get("_cell_length_a")
    b = _get("_cell_length_b")
    c = _get("_cell_length_c")
    alpha = _get("_cell_angle_alpha")
    beta  = _get("_cell_angle_beta")
    gamma = _get("_cell_angle_gamma")

    lines: list[str] = []
    if formula != "?":
        lines.append(f"Formula:      {formula}")
    lines.append(f"Space group:  {sg}")
    lines.append(f"a = {a}  b = {b}  c = {c} Å")
    lines.append(f"α = {alpha}  β = {beta}  γ = {gamma}°")
    return "\n".join(lines)


# ── Crystal phase form ────────────────────────────────────────────────────────

class _CrystalPhaseForm(QWidget):
    """Inline form for registering a crystal species artefact.

    The CIF file is chosen from the campaign's ingested CIF assets (populated
    via :meth:`refreshCifAssets`).  A small preview panel shows the crystal
    structure summary of the currently selected CIF.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        # ── Basic fields ───────────────────────────────────────────────
        basic = QWidget()
        form = QFormLayout(basic)
        form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        self._nameEdit = QLineEdit()
        self._nameEdit.setPlaceholderText('e.g. "ice-VII" or "Si-calibrant"')
        form.addRow("Species name:", self._nameEdit)

        self._roleCombo = QComboBox()
        self._roleCombo.addItem("Sample", userData="sample")
        self._roleCombo.addItem("Calibrant", userData="calibrant")
        form.addRow("Role:", self._roleCombo)

        # CIF picker — populated from ingested CIF assets
        self._cifCombo = QComboBox()
        self._cifCombo.setMinimumWidth(200)
        self._cifCombo.currentIndexChanged.connect(self._onCifChanged)
        form.addRow("CIF asset:", self._cifCombo)

        # Crystal structure preview for the selected CIF.
        # Fixed-height QPlainTextEdit avoids the height-for-width instability
        # that QLabel(wordWrap=True) introduces in QFormLayout.
        self._cifPreview = QPlainTextEdit()
        self._cifPreview.setReadOnly(True)
        self._cifPreview.setFixedHeight(62)
        self._cifPreview.setFrameShape(QFrame.NoFrame)
        self._cifPreview.setStyleSheet("color: gray; background: transparent;")
        form.addRow("", self._cifPreview)

        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        form.addRow("Run number:", self._runEdit)

        layout.addWidget(basic)

        # ── EOS sub-form ───────────────────────────────────────────────
        self._eosForm = _EosSubForm()
        layout.addWidget(self._eosForm)

        # Seed with empty state (no assets yet)
        self._populateNoCif()

    def _populateNoCif(self) -> None:
        self._cifCombo.clear()
        self._cifCombo.addItem("No CIF assets — ingest a CIF file first")
        self._cifCombo.setEnabled(False)
        self._cifPreview.clear()

    def refreshCifAssets(self, assets: list[dict[str, Any]]) -> None:
        """Repopulate the CIF picker from the current asset list.

        Called by :class:`SetupPanel` whenever the asset table is refreshed.
        Only records whose ``asset_type == "cif"`` are shown.
        """
        cif_assets = [a for a in assets if a.get("asset_type") == "cif"]
        self._cifCombo.blockSignals(True)
        self._cifCombo.clear()
        if not cif_assets:
            self._populateNoCif()
        else:
            self._cifCombo.setEnabled(True)
            for rec in cif_assets:
                label = rec.get("asset_id") or Path(rec.get("path", "?")).name
                self._cifCombo.addItem(label, userData=rec)
                path = rec.get("path", "")
                if path:
                    preview = _cif_preview_text(path)
                    if preview:
                        self._cifCombo.setItemData(
                            self._cifCombo.count() - 1, preview, Qt.ToolTipRole
                        )
        self._cifCombo.blockSignals(False)
        self._onCifChanged(self._cifCombo.currentIndex())

    def _onCifChanged(self, index: int) -> None:
        rec = self._cifCombo.itemData(index)
        if not isinstance(rec, dict):
            self._cifPreview.clear()
            return
        path = rec.get("path", "")
        self._cifPreview.setPlainText(_cif_preview_text(path) if path else "")

    def params(self) -> dict[str, Any]:
        rec = self._cifCombo.currentData()
        cif_path = rec.get("path", "") if isinstance(rec, dict) else ""
        run_text = self._runEdit.text().strip()
        try:
            source_run: int | None = int(run_text) if run_text else None
        except ValueError:
            source_run = None
        return {
            "species_name": self._nameEdit.text().strip(),
            "role": self._roleCombo.currentData(),
            "cif_path": cif_path,
            "eos_params": self._eosForm.params(),
            "source_run": source_run,
        }

    def validate(self) -> str | None:
        p = self.params()
        if not p["species_name"]:
            return "Species name is required."
        if not p["cif_path"]:
            return "No CIF asset selected — ingest a CIF file in the Assets section first."
        return self._eosForm.validate()


# ── Setup panel ───────────────────────────────────────────────────────────────

class SetupPanel(QWidget):
    """Setup tab: assets table + artefact creation forms.

    Signals
    -------
    ingestRequested()
        Emitted when the operator clicks "Ingest asset…".
    refreshRequested()
        Emitted when the operator clicks Refresh.
    pixelMaskRegistrationRequested(dict)
        Emitted with the validated form parameters when operator clicks
        Register for a pixel mask.
    """

    ingestRequested = Signal()
    refreshRequested = Signal()
    assetDeleteRequested = Signal(str)   # emits asset_id
    pixelMaskRegistrationRequested = Signal(dict)
    crystalSpeciesRegistrationRequested = Signal(dict)
    binMaskFromMonitorRequested = Signal(dict)
    binMaskManualRequested = Signal(dict)
    binMaskFromWorkspaceRequested = Signal(dict)
    binMaskFromJsonRequested = Signal(dict)

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)

        # ── Assets group ───────────────────────────────────────────────
        assets_group = QGroupBox("Assets")
        ag_layout = QVBoxLayout(assets_group)

        toolbar = QHBoxLayout()
        toolbar.addStretch(1)
        self._deleteBtn = QPushButton("Delete asset")
        self._deleteBtn.setToolTip("Permanently remove the selected asset from the index")
        self._deleteBtn.setEnabled(False)
        self._deleteBtn.clicked.connect(self._onDeleteAsset)
        toolbar.addWidget(self._deleteBtn)
        self._ingestBtn = QPushButton("Ingest asset…")
        self._ingestBtn.setToolTip("Copy a file into the managed asset store")
        self._ingestBtn.clicked.connect(self.ingestRequested)
        toolbar.addWidget(self._ingestBtn)
        self._refreshBtn = QPushButton("Refresh")
        self._refreshBtn.clicked.connect(self.refreshRequested)
        toolbar.addWidget(self._refreshBtn)
        ag_layout.addLayout(toolbar)

        self._assetModel = _AssetTableModel([])
        self._assetView = QTableView()
        self._assetView.setModel(self._assetModel)
        self._assetView.setSelectionBehavior(QTableView.SelectRows)
        self._assetView.setSelectionMode(QTableView.SingleSelection)
        self._assetView.setEditTriggers(QTableView.NoEditTriggers)
        self._assetView.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        self._assetView.verticalHeader().setVisible(False)
        self._assetView.selectionModel().selectionChanged.connect(self._onAssetSelectionChanged)
        ag_layout.addWidget(self._assetView)

        layout.addWidget(assets_group)

        # ── Artefact creation group ────────────────────────────────────
        creation_group = QGroupBox("Artefact creation")
        cg_layout = QVBoxLayout(creation_group)

        type_row = QHBoxLayout()
        type_row.addWidget(QLabel("Type:"))
        self._typeCombo = QComboBox()
        self._typeCombo.addItem("Pixel mask")
        self._typeCombo.addItem("Crystal phase")
        self._typeCombo.addItem("Bin mask (transmission monitor)")
        self._typeCombo.addItem("Bin mask (manual notch list)")
        self._typeCombo.addItem("Bin mask (from workspace history)")
        self._typeCombo.addItem("Bin mask (from JSON file)")
        self._typeCombo.currentIndexChanged.connect(self._onTypeChanged)
        type_row.addWidget(self._typeCombo)
        type_row.addStretch(1)
        cg_layout.addLayout(type_row)

        # Stacked forms — one page per artefact type
        self._stack = QStackedWidget()

        self._pixelMaskForm = _PixelMaskForm()
        self._stack.addWidget(self._pixelMaskForm)   # index 0 = _TYPE_PIXEL_MASK

        self._crystalPhaseForm = _CrystalPhaseForm()
        self._stack.addWidget(self._crystalPhaseForm)  # index 1 = _TYPE_CRYSTAL_PHASE

        self._binMaskMonitorForm = _BinMaskFromMonitorForm()
        self._stack.addWidget(self._binMaskMonitorForm)  # index 2 = _TYPE_BIN_MASK_MONITOR

        self._binMaskManualForm = _BinMaskManualForm()
        self._stack.addWidget(self._binMaskManualForm)  # index 3 = _TYPE_BIN_MASK_MANUAL

        self._binMaskFromWorkspaceForm = _BinMaskFromWorkspaceForm()
        self._stack.addWidget(self._binMaskFromWorkspaceForm)  # index 4 = _TYPE_BIN_MASK_WORKSPACE

        self._binMaskFromJsonForm = _BinMaskFromJsonForm()
        self._stack.addWidget(self._binMaskFromJsonForm)  # index 5 = _TYPE_BIN_MASK_JSON

        cg_layout.addWidget(self._stack)

        btn_row = QHBoxLayout()
        btn_row.addStretch(1)
        self._createBtn = QPushButton("Register")
        self._createBtn.clicked.connect(self._onRegister)
        btn_row.addWidget(self._createBtn)
        cg_layout.addLayout(btn_row)

        # Wrap in a scroll area so expanding EOS never fights the assets table
        # for vertical space — the form scrolls rather than compressing.
        creation_scroll = QScrollArea()
        creation_scroll.setWidgetResizable(True)
        creation_scroll.setFrameShape(QFrame.NoFrame)
        creation_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        creation_scroll.setWidget(creation_group)
        layout.addWidget(creation_scroll)

    # ── Public API ─────────────────────────────────────────────────────

    def setIPTS(self, ipts: int | None) -> None:
        """Set the current IPTS so the JSON file browser opens in the right folder."""
        if ipts is not None:
            default_dir = f"/SNS/SNAP/IPTS-{ipts}/shared"
        else:
            default_dir = ""
        self._binMaskFromJsonForm.setDefaultDir(default_dir)

    def setRows(self, rows: list[dict[str, Any]]) -> None:
        self._assetModel.setRows(rows)
        self._crystalPhaseForm.refreshCifAssets(rows)

    # ── Internal slots ─────────────────────────────────────────────────

    def _onAssetSelectionChanged(self) -> None:
        self._deleteBtn.setEnabled(bool(self._assetView.selectionModel().selectedRows()))

    def _onDeleteAsset(self) -> None:
        rows = self._assetView.selectionModel().selectedRows()
        if not rows:
            return
        asset_id = self._assetModel._rows[rows[0].row()].get("asset_id", "")
        if asset_id:
            self.assetDeleteRequested.emit(asset_id)

    def _onTypeChanged(self, index: int) -> None:
        self._stack.setCurrentIndex(index)

    def _onRegister(self) -> None:
        from qtpy.QtWidgets import QMessageBox  # type: ignore
        index = self._typeCombo.currentIndex()
        if index == _TYPE_PIXEL_MASK:
            error = self._pixelMaskForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.pixelMaskRegistrationRequested.emit(self._pixelMaskForm.params())
        elif index == _TYPE_CRYSTAL_PHASE:
            error = self._crystalPhaseForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.crystalSpeciesRegistrationRequested.emit(self._crystalPhaseForm.params())
        elif index == _TYPE_BIN_MASK_MONITOR:
            error = self._binMaskMonitorForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.binMaskFromMonitorRequested.emit(self._binMaskMonitorForm.params())
        elif index == _TYPE_BIN_MASK_MANUAL:
            error = self._binMaskManualForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.binMaskManualRequested.emit(self._binMaskManualForm.params())
        elif index == _TYPE_BIN_MASK_WORKSPACE:
            error = self._binMaskFromWorkspaceForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.binMaskFromWorkspaceRequested.emit(self._binMaskFromWorkspaceForm.params())
        elif index == _TYPE_BIN_MASK_JSON:
            error = self._binMaskFromJsonForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.binMaskFromJsonRequested.emit(self._binMaskFromJsonForm.params())
