"""Setup panel for the Campaign Manager.

Phase 4a: Assets table with Ingest button.
Phase 4b: Pixel mask registration form.
Phase 4c (pending): Crystal phase builder.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from qtpy.QtCore import QAbstractTableModel, QModelIndex, Qt, Signal  # type: ignore
from qtpy.QtWidgets import (  # type: ignore
    QCheckBox,
    QComboBox,
    QFileDialog,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QPlainTextEdit,
    QPushButton,
    QStackedWidget,
    QTableView,
    QVBoxLayout,
    QWidget,
)

_ASSET_COLUMNS = ["Asset ID", "Type", "Scope", "Status"]

# Artefact-type combo indices
_TYPE_PIXEL_MASK = 0
_TYPE_CRYSTAL_PHASE = 1


# ── Assets table ──────────────────────────────────────────────────────────────

class _AssetTableModel(QAbstractTableModel):
    def __init__(self, rows: list[dict[str, Any]], parent=None) -> None:
        super().__init__(parent)
        self._rows = rows

    def setRows(self, rows: list[dict[str, Any]]) -> None:
        self.beginResetModel()
        self._rows = rows
        self.endResetModel()

    def rowCount(self, parent: QModelIndex = QModelIndex()) -> int:  # noqa: B008
        return 0 if parent.isValid() else len(self._rows)

    def columnCount(self, parent: QModelIndex = QModelIndex()) -> int:  # noqa: B008
        return 0 if parent.isValid() else len(_ASSET_COLUMNS)

    def headerData(self, section: int, orientation: Qt.Orientation, role: int = Qt.DisplayRole) -> Any:
        if role == Qt.DisplayRole and orientation == Qt.Horizontal:
            return _ASSET_COLUMNS[section]
        return None

    def data(self, index: QModelIndex, role: int = Qt.DisplayRole) -> Any:
        if not index.isValid() or role != Qt.DisplayRole:
            return None
        row = self._rows[index.row()]
        col = index.column()
        if col == 0:
            return row.get("asset_id", "")
        if col == 1:
            return row.get("asset_type", "")
        if col == 2:
            app = row.get("applicability") or {}
            scope = app.get("scope", "campaign")
            rn = app.get("run_number")
            return f"run {rn}" if scope == "run" and rn is not None else "campaign"
        if col == 3:
            return row.get("status", "")
        return None


# ── Pixel mask form ───────────────────────────────────────────────────────────

class _PixelMaskForm(QWidget):
    """Inline form for registering a pixel mask artefact.

    The artefact ID is auto-generated by the model from the method, source
    stem, and lite/native tag — the operator does not need to invent one.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QFormLayout(self)
        layout.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        # isLite toggle (default True)
        self._liteCheck = QCheckBox("Lite mode")
        self._liteCheck.setChecked(True)
        self._liteCheck.setToolTip(
            "Lite (18 432-pixel) and native (1 179 648-pixel) masks are "
            "incompatible — ensure this matches your reduction mode."
        )
        layout.addRow("Instrument mode:", self._liteCheck)

        # Method
        self._methodCombo = QComboBox()
        self._methodCombo.addItem("Standard PE (letterbox)", userData="pixel_mask.letterbox")
        self._methodCombo.addItem("Custom .nxs file", userData="pixel_mask.custom")
        self._methodCombo.addItem("ADS workspace", userData="pixel_mask.workspace")
        self._methodCombo.currentIndexChanged.connect(self._onMethodChanged)
        layout.addRow("Source:", self._methodCombo)

        # File path (custom only)
        self._fileRow = QWidget()
        file_layout = QHBoxLayout(self._fileRow)
        file_layout.setContentsMargins(0, 0, 0, 0)
        self._fileEdit = QLineEdit()
        self._fileEdit.setPlaceholderText("Path to .nxs pixel mask file")
        file_layout.addWidget(self._fileEdit)
        browse_btn = QPushButton("Browse…")
        browse_btn.clicked.connect(self._onBrowse)
        file_layout.addWidget(browse_btn)
        self._fileLabel = QLabel("File:")
        layout.addRow(self._fileLabel, self._fileRow)
        self._fileLabel.setVisible(False)
        self._fileRow.setVisible(False)

        # ADS workspace picker
        self._wsPickRow = QWidget()
        ws_pick_layout = QHBoxLayout(self._wsPickRow)
        ws_pick_layout.setContentsMargins(0, 0, 0, 0)
        self._wsPickCombo = QComboBox()
        self._wsPickCombo.setMinimumWidth(220)
        ws_pick_layout.addWidget(self._wsPickCombo, stretch=1)
        refresh_btn = QPushButton("Refresh")
        refresh_btn.setToolTip("Reload workspace list from the Mantid ADS")
        refresh_btn.clicked.connect(self._refreshWorkspaces)
        ws_pick_layout.addWidget(refresh_btn)
        self._wsPickLabel = QLabel("Workspace:")
        layout.addRow(self._wsPickLabel, self._wsPickRow)
        self._wsPickLabel.setVisible(False)
        self._wsPickRow.setVisible(False)

        # Mantid workspace name (used during reduction to load the mask)
        self._wsNameEdit = QLineEdit()
        self._wsNameEdit.setText("pixmask_pe")
        self._wsNameEdit.setPlaceholderText("Mantid workspace name for reduction")
        layout.addRow("Workspace name:", self._wsNameEdit)

        # Run number (optional)
        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        layout.addRow("Run number:", self._runEdit)

        # Notes
        self._notesEdit = QPlainTextEdit()
        self._notesEdit.setPlaceholderText("Optional notes")
        self._notesEdit.setFixedHeight(55)
        layout.addRow("Notes:", self._notesEdit)

        # Seed the workspace list on construction
        self._refreshWorkspaces()

    def _onBrowse(self) -> None:
        path, _ = QFileDialog.getOpenFileName(
            self, "Select pixel mask file", "", "Nexus files (*.nxs);;All files (*)"
        )
        if path:
            self._fileEdit.setText(path)

    def _refreshWorkspaces(self) -> None:
        """Populate the ADS workspace combo from the Mantid ADS."""
        self._wsPickCombo.clear()
        try:
            from mantid.api import AnalysisDataService as ADS  # type: ignore
            names = sorted(ADS.getObjectNames())
        except Exception:
            names = []
        for name in names:
            self._wsPickCombo.addItem(name)
        if not names:
            self._wsPickCombo.addItem("(no workspaces in ADS)")

    def _onMethodChanged(self, _index: int) -> None:
        method = self._methodCombo.currentData()
        is_custom = method == "pixel_mask.custom"
        is_workspace = method == "pixel_mask.workspace"
        is_letterbox = method == "pixel_mask.letterbox"

        self._fileLabel.setVisible(is_custom)
        self._fileRow.setVisible(is_custom)
        self._wsPickLabel.setVisible(is_workspace)
        self._wsPickRow.setVisible(is_workspace)

        # PE letterbox mask is lite — lock the toggle to reflect that
        if is_letterbox:
            self._liteCheck.setChecked(True)
            self._liteCheck.setEnabled(False)
            self._wsNameEdit.setText("pixmask_pe")
        else:
            self._liteCheck.setEnabled(True)
            self._wsNameEdit.setText(
                "pixmask_ws" if is_workspace else "pixmask_custom"
            )

    def params(self) -> dict[str, Any]:
        method = self._methodCombo.currentData()
        run_text = self._runEdit.text().strip()
        try:
            run_number: int | None = int(run_text) if run_text else None
        except ValueError:
            run_number = None
        p: dict[str, Any] = {
            "method": method,
            "is_lite": self._liteCheck.isChecked(),
            "ws_name": self._wsNameEdit.text().strip(),
            "run_number": run_number,
            "notes": self._notesEdit.toPlainText().strip() or None,
        }
        if method == "pixel_mask.custom":
            p["nxs_path"] = self._fileEdit.text().strip()
        elif method == "pixel_mask.workspace":
            p["ads_workspace"] = self._wsPickCombo.currentText()
        return p

    def validate(self) -> str | None:
        """Return an error message, or None if the form is valid."""
        p = self.params()
        if not p["ws_name"]:
            return "Workspace name is required."
        if p["method"] == "pixel_mask.custom" and not p.get("nxs_path"):
            return "A .nxs file path is required for the custom method."
        if p["method"] == "pixel_mask.workspace" and p.get("ads_workspace", "").startswith("("):
            return "Select a workspace from the ADS list."
        return None


# ── EOS sub-form ──────────────────────────────────────────────────────────────

_V0_UNIT_CELL = "Å³/unit cell"
_V0_UNIT_ATOM = "Å³/atom"
_V0_UNIT_MOL  = "cm³/mol"

# 1 cm³/mol → Å³ per formula unit (Z=1):  1e24 Å³ / 6.02214076e23
_CM3_MOL_TO_A3 = 1e24 / 6.02214076e23  # ≈ 1.66054


class _EosSubForm(QGroupBox):
    """Optional checkable EOS group for _CrystalPhaseForm.

    Unchecked by default (EOS is optional).  When checked the operator
    provides EOS type, V₀ (with unit conversion), K₀, K', a mandatory
    literature reference, and optional stability bounds.
    """

    def __init__(self, parent=None) -> None:
        super().__init__("Equation of state", parent)
        self.setCheckable(True)
        self.setChecked(False)
        self.setToolTip("Tick to provide EOS parameters for pressure work.")

        outer = QVBoxLayout(self)
        outer.setContentsMargins(4, 4, 4, 4)

        # All form content lives in this widget, shown/hidden by the checkbox.
        self._content = QWidget()
        outer.addWidget(self._content)
        self._content.setVisible(False)
        self.toggled.connect(self._content.setVisible)

        layout = QFormLayout(self._content)
        layout.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        # EOS type
        self._typeCombo = QComboBox()
        self._typeCombo.addItem("Birch-Murnaghan", userData="birch-murnaghan")
        self._typeCombo.addItem("Vinet", userData="vinet")
        self._typeCombo.addItem("Murnaghan", userData="murnaghan")
        layout.addRow("EOS type:", self._typeCombo)

        # V₀ with unit selector
        v0_row = QWidget()
        v0_layout = QHBoxLayout(v0_row)
        v0_layout.setContentsMargins(0, 0, 0, 0)
        self._v0Edit = QLineEdit()
        self._v0Edit.setPlaceholderText("e.g. 15.862")
        v0_layout.addWidget(self._v0Edit, stretch=2)
        self._v0UnitCombo = QComboBox()
        self._v0UnitCombo.addItem(_V0_UNIT_CELL)
        self._v0UnitCombo.addItem(_V0_UNIT_ATOM)
        self._v0UnitCombo.addItem(_V0_UNIT_MOL)
        self._v0UnitCombo.currentIndexChanged.connect(self._onUnitChanged)
        v0_layout.addWidget(self._v0UnitCombo, stretch=1)
        layout.addRow("V₀:", v0_row)

        # Z — shown only when unit requires conversion
        self._zLabel = QLabel("Z (formula units/cell):")
        self._zEdit = QLineEdit()
        self._zEdit.setPlaceholderText("positive integer, e.g. 2")
        self._zEdit.setToolTip(
            "Number of formula units per unit cell.\n"
            "Required to convert from per-atom or per-mol units."
        )
        layout.addRow(self._zLabel, self._zEdit)
        self._zLabel.setVisible(False)
        self._zEdit.setVisible(False)

        # K₀
        self._k0Edit = QLineEdit()
        self._k0Edit.setPlaceholderText("bulk modulus in GPa, e.g. 295.2")
        layout.addRow("K₀ (GPa):", self._k0Edit)

        # K'
        self._kpEdit = QLineEdit()
        self._kpEdit.setPlaceholderText("pressure derivative, e.g. 4.32")
        layout.addRow("K′ (dimensionless):", self._kpEdit)

        # Reference (mandatory when EOS enabled)
        self._sourceEdit = QLineEdit()
        self._sourceEdit.setPlaceholderText(
            "e.g. Dewaele et al., PRB 70 094112 (2004)"
        )
        layout.addRow("Reference (required):", self._sourceEdit)

        # Stability bounds header
        stab_label = QLabel(
            "<i>Approximate stability bounds for your experimental conditions</i> (all optional):"
        )
        stab_label.setWordWrap(True)
        layout.addRow(stab_label)

        # Pressure bounds
        p_row = QWidget()
        p_layout = QHBoxLayout(p_row)
        p_layout.setContentsMargins(0, 0, 0, 0)
        self._pMinEdit = QLineEdit()
        self._pMinEdit.setPlaceholderText("P_min")
        self._pMaxEdit = QLineEdit()
        self._pMaxEdit.setPlaceholderText("P_max")
        p_layout.addWidget(QLabel("P_min:"))
        p_layout.addWidget(self._pMinEdit)
        p_layout.addSpacing(8)
        p_layout.addWidget(QLabel("P_max:"))
        p_layout.addWidget(self._pMaxEdit)
        layout.addRow("Pressure (GPa):", p_row)

        # Temperature bounds
        t_row = QWidget()
        t_layout = QHBoxLayout(t_row)
        t_layout.setContentsMargins(0, 0, 0, 0)
        self._tMinEdit = QLineEdit()
        self._tMinEdit.setPlaceholderText("T_min")
        self._tMaxEdit = QLineEdit()
        self._tMaxEdit.setPlaceholderText("T_max")
        t_layout.addWidget(QLabel("T_min:"))
        t_layout.addWidget(self._tMinEdit)
        t_layout.addSpacing(8)
        t_layout.addWidget(QLabel("T_max:"))
        t_layout.addWidget(self._tMaxEdit)
        layout.addRow("Temperature (K):", t_row)

    def _onUnitChanged(self, _index: int) -> None:
        needs_z = self._v0UnitCombo.currentText() != _V0_UNIT_CELL
        self._zLabel.setVisible(needs_z)
        self._zEdit.setVisible(needs_z)

    @staticmethod
    def _opt_float(edit: QLineEdit) -> float | None:
        t = edit.text().strip()
        if not t:
            return None
        try:
            return float(t)
        except ValueError:
            return None

    def _v0_in_cell_units(self) -> float | None:
        v0 = self._opt_float(self._v0Edit)
        if v0 is None:
            return None
        unit = self._v0UnitCombo.currentText()
        if unit == _V0_UNIT_CELL:
            return v0
        try:
            z = int(self._zEdit.text().strip())
        except ValueError:
            return None
        if z <= 0:
            return None
        if unit == _V0_UNIT_ATOM:
            return v0 * z
        return v0 * z * _CM3_MOL_TO_A3  # cm³/mol

    def params(self) -> dict[str, Any] | None:
        """Return EOS params dict, or None if the group is unchecked."""
        if not self.isChecked():
            return None
        p_min = self._opt_float(self._pMinEdit)
        p_max = self._opt_float(self._pMaxEdit)
        t_min = self._opt_float(self._tMinEdit)
        t_max = self._opt_float(self._tMaxEdit)
        return {
            "eos_type": self._typeCombo.currentData(),
            "V_0": self._v0_in_cell_units(),
            "K_0": self._opt_float(self._k0Edit),
            "K_prime": self._opt_float(self._kpEdit),
            "source": self._sourceEdit.text().strip(),
            "stability_pressure": [p_min, p_max] if (p_min is not None or p_max is not None) else None,
            "stability_temperature": [t_min, t_max] if (t_min is not None or t_max is not None) else None,
        }

    def validate(self) -> str | None:
        if not self.isChecked():
            return None
        v0_raw = self._opt_float(self._v0Edit)
        if v0_raw is None:
            return "V₀ is required."
        if v0_raw <= 0:
            return "V₀ must be positive."
        if self._v0UnitCombo.currentText() != _V0_UNIT_CELL:
            try:
                z = int(self._zEdit.text().strip())
                if z <= 0:
                    raise ValueError
            except ValueError:
                return "Z (formula units/cell) must be a positive integer for the selected unit."
        k0 = self._opt_float(self._k0Edit)
        if k0 is None:
            return "K₀ is required."
        if k0 <= 0:
            return "K₀ must be positive (GPa)."
        if self._opt_float(self._kpEdit) is None:
            return "K′ is required."
        if not self._sourceEdit.text().strip():
            return "A literature reference is required for the EOS."
        return None


# ── CIF preview helper ────────────────────────────────────────────────────────

def _cif_preview_text(path: str) -> str:
    """Return a tooltip-friendly crystal summary extracted from a CIF file.

    Uses simple regex extraction — no Mantid required.  Returns an empty
    string if the file cannot be read or parsed.
    """
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""

    def _get(*keys: str) -> str:
        for key in keys:
            m = re.search(
                rf"^{re.escape(key)}\s+['\"]?([^'\"\n]+)['\"]?",
                text,
                re.MULTILINE | re.IGNORECASE,
            )
            if m:
                return m.group(1).strip()
        return "?"

    sg = _get(
        "_symmetry_space_group_name_H-M",
        "_space_group_name_H-M_alt",
        "_symmetry_space_group_name_h-m",
    )
    formula = _get(
        "_chemical_formula_sum",
        "_chemical_name_mineral",
        "_chemical_formula_structural",
    )
    a = _get("_cell_length_a")
    b = _get("_cell_length_b")
    c = _get("_cell_length_c")
    alpha = _get("_cell_angle_alpha")
    beta  = _get("_cell_angle_beta")
    gamma = _get("_cell_angle_gamma")

    lines: list[str] = []
    if formula != "?":
        lines.append(f"Formula:      {formula}")
    lines.append(f"Space group:  {sg}")
    lines.append(f"a = {a}  b = {b}  c = {c} Å")
    lines.append(f"α = {alpha}  β = {beta}  γ = {gamma}°")
    return "\n".join(lines)


# ── Crystal phase form ────────────────────────────────────────────────────────

class _CrystalPhaseForm(QWidget):
    """Inline form for registering a crystal species artefact."""

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        # ── Basic fields ───────────────────────────────────────────────
        basic = QWidget()
        form = QFormLayout(basic)
        form.setLabelAlignment(Qt.AlignRight | Qt.AlignVCenter)

        self._nameEdit = QLineEdit()
        self._nameEdit.setPlaceholderText('e.g. "ice-VII" or "Si-calibrant"')
        form.addRow("Species name:", self._nameEdit)

        self._roleCombo = QComboBox()
        self._roleCombo.addItem("Sample", userData="sample")
        self._roleCombo.addItem("Calibrant", userData="calibrant")
        form.addRow("Role:", self._roleCombo)

        cif_row = QWidget()
        cif_layout = QHBoxLayout(cif_row)
        cif_layout.setContentsMargins(0, 0, 0, 0)
        self._cifEdit = QLineEdit()
        self._cifEdit.setPlaceholderText("Path to .cif file (required)")
        cif_layout.addWidget(self._cifEdit)
        cif_btn = QPushButton("Browse…")
        cif_btn.clicked.connect(self._onBrowseCif)
        cif_layout.addWidget(cif_btn)
        form.addRow("CIF file:", cif_row)

        self._runEdit = QLineEdit()
        self._runEdit.setPlaceholderText("optional — leave blank for campaign-wide")
        form.addRow("Run number:", self._runEdit)

        layout.addWidget(basic)

        # ── EOS sub-form ───────────────────────────────────────────────
        self._eosForm = _EosSubForm()
        layout.addWidget(self._eosForm)

    def _onBrowseCif(self) -> None:
        path, _ = QFileDialog.getOpenFileName(
            self, "Select CIF file", "", "CIF files (*.cif);;All files (*)"
        )
        if path:
            self._cifEdit.setText(path)
            preview = _cif_preview_text(path)
            self._cifEdit.setToolTip(preview if preview else path)

    def params(self) -> dict[str, Any]:
        run_text = self._runEdit.text().strip()
        try:
            source_run: int | None = int(run_text) if run_text else None
        except ValueError:
            source_run = None
        return {
            "species_name": self._nameEdit.text().strip(),
            "role": self._roleCombo.currentData(),
            "cif_path": self._cifEdit.text().strip(),
            "eos_params": self._eosForm.params(),
            "source_run": source_run,
        }

    def validate(self) -> str | None:
        p = self.params()
        if not p["species_name"]:
            return "Species name is required."
        if not p["cif_path"]:
            return "A CIF file is required."
        return self._eosForm.validate()


# ── Setup panel ───────────────────────────────────────────────────────────────

class SetupPanel(QWidget):
    """Setup tab: assets table + artefact creation forms.

    Signals
    -------
    ingestRequested()
        Emitted when the operator clicks "Ingest asset…".
    refreshRequested()
        Emitted when the operator clicks Refresh.
    pixelMaskRegistrationRequested(dict)
        Emitted with the validated form parameters when operator clicks
        Register for a pixel mask.
    """

    ingestRequested = Signal()
    refreshRequested = Signal()
    assetDeleteRequested = Signal(str)   # emits asset_id
    pixelMaskRegistrationRequested = Signal(dict)
    crystalSpeciesRegistrationRequested = Signal(dict)

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        layout = QVBoxLayout(self)

        # ── Assets group ───────────────────────────────────────────────
        assets_group = QGroupBox("Assets")
        ag_layout = QVBoxLayout(assets_group)

        toolbar = QHBoxLayout()
        toolbar.addStretch(1)
        self._deleteBtn = QPushButton("Delete asset")
        self._deleteBtn.setToolTip("Permanently remove the selected asset from the index")
        self._deleteBtn.setEnabled(False)
        self._deleteBtn.clicked.connect(self._onDeleteAsset)
        toolbar.addWidget(self._deleteBtn)
        self._ingestBtn = QPushButton("Ingest asset…")
        self._ingestBtn.setToolTip("Copy a file into the managed asset store")
        self._ingestBtn.clicked.connect(self.ingestRequested)
        toolbar.addWidget(self._ingestBtn)
        self._refreshBtn = QPushButton("Refresh")
        self._refreshBtn.clicked.connect(self.refreshRequested)
        toolbar.addWidget(self._refreshBtn)
        ag_layout.addLayout(toolbar)

        self._assetModel = _AssetTableModel([])
        self._assetView = QTableView()
        self._assetView.setModel(self._assetModel)
        self._assetView.setSelectionBehavior(QTableView.SelectRows)
        self._assetView.setSelectionMode(QTableView.SingleSelection)
        self._assetView.setEditTriggers(QTableView.NoEditTriggers)
        self._assetView.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        self._assetView.verticalHeader().setVisible(False)
        self._assetView.selectionModel().selectionChanged.connect(self._onAssetSelectionChanged)
        ag_layout.addWidget(self._assetView)

        layout.addWidget(assets_group)

        # ── Artefact creation group ────────────────────────────────────
        creation_group = QGroupBox("Artefact creation")
        cg_layout = QVBoxLayout(creation_group)

        type_row = QHBoxLayout()
        type_row.addWidget(QLabel("Type:"))
        self._typeCombo = QComboBox()
        self._typeCombo.addItem("Pixel mask")
        self._typeCombo.addItem("Crystal phase")
        self._typeCombo.currentIndexChanged.connect(self._onTypeChanged)
        type_row.addWidget(self._typeCombo)
        type_row.addStretch(1)
        cg_layout.addLayout(type_row)

        # Stacked forms — one page per artefact type
        self._stack = QStackedWidget()

        self._pixelMaskForm = _PixelMaskForm()
        self._stack.addWidget(self._pixelMaskForm)   # index 0 = _TYPE_PIXEL_MASK

        self._crystalPhaseForm = _CrystalPhaseForm()
        self._stack.addWidget(self._crystalPhaseForm)  # index 1 = _TYPE_CRYSTAL_PHASE

        cg_layout.addWidget(self._stack)

        btn_row = QHBoxLayout()
        btn_row.addStretch(1)
        self._createBtn = QPushButton("Register")
        self._createBtn.clicked.connect(self._onRegister)
        btn_row.addWidget(self._createBtn)
        cg_layout.addLayout(btn_row)

        layout.addWidget(creation_group)

    # ── Public API ─────────────────────────────────────────────────────

    def setRows(self, rows: list[dict[str, Any]]) -> None:
        self._assetModel.setRows(rows)

    # ── Internal slots ─────────────────────────────────────────────────

    def _onAssetSelectionChanged(self) -> None:
        self._deleteBtn.setEnabled(bool(self._assetView.selectionModel().selectedRows()))

    def _onDeleteAsset(self) -> None:
        rows = self._assetView.selectionModel().selectedRows()
        if not rows:
            return
        asset_id = self._assetModel._rows[rows[0].row()].get("asset_id", "")
        if asset_id:
            self.assetDeleteRequested.emit(asset_id)

    def _onTypeChanged(self, index: int) -> None:
        self._stack.setCurrentIndex(index)

    def _onRegister(self) -> None:
        from qtpy.QtWidgets import QMessageBox  # type: ignore
        index = self._typeCombo.currentIndex()
        if index == _TYPE_PIXEL_MASK:
            error = self._pixelMaskForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.pixelMaskRegistrationRequested.emit(self._pixelMaskForm.params())
        elif index == _TYPE_CRYSTAL_PHASE:
            error = self._crystalPhaseForm.validate()
            if error:
                QMessageBox.warning(self, "Invalid form", error)
                return
            self.crystalSpeciesRegistrationRequested.emit(self._crystalPhaseForm.params())
