"""Reduction artefacts runtime support.

This package hosts executable contracts and helpers for reduction artefact
persistence/validation. Schema files are intentionally colocated here (not in
`docs/`) because they are consumed by runtime tooling.
"""

from .persistence import (
	SlugConflictError,
	add_candidate_species,
	annotate_run,
	append_jsonl_record,
	bootstrap_campaign,
	bootstrap_campaign_from_manifest,
	build_run_manifest,
	copy_artefact,
	copy_to_asset_store,
	get_campaign_artefact_dir,
	get_campaign_paths,
	ingest_asset,
	ingest_seemeta_for_run,
	list_asset_records,
	list_artefact_records,
	list_campaigns,
	list_crystal_species_records,
	register_asset_record,
	register_attenuation_artefact_planned,
	register_crystal_species_artefact,
	register_manual_bin_mask_artefact,
	register_swiss_cheese_artefact,
	register_pixel_mask_artefact,
	rename_campaign_slug,
	retire_artefact,
	reset_artefacts_index,
	read_jsonl_records,
	resolve_campaign_slug,
	validate_jsonl_file,
	validate_record,
)
from .assets import (
	ApplicabilityScope,
	AssetApplicability,
	AssetRecord,
	AssetStatus,
	AssetType,
	LoadedAsset,
)
from .asset_artefact_examples import (
	ArtefactDefinition,
	AssetArtefactExample,
	AssetDefinition,
	EOSObject,
	PixelMaskWorkspaceObject,
	SwissCheeseObject,
	build_crystal_species_from_cif,
	build_crystal_species_from_cif_and_eos,
	build_example_artefact,
	list_asset_artefact_examples,
)
from .builders import (
	build_crystal_species,
	load_eos_description,
	load_phase_description,
)
from .masking import (
	build_swiss_cheese_from_run,
	build_swiss_cheese_from_ub_files,
	build_swiss_cheese_from_transmission_monitor,
	detect_notches_in_spectrum,
)
from .requirements import (
	build_requirement_report,
	build_requirement_report_from_seemeta,
	generate_requirement_reports_from_campaign_specs,
	generate_requirement_report_for_run,
	get_requirement_specs,
	infer_assembly_type_from_run,
	infer_assembly_type_from_seemeta,
	normalize_assembly_type,
	preflight_campaign_specs_seemeta,
)
from .schema_paths import get_schema_path, list_schema_paths
from .campaign_setup import (
	auto_register_bin_mask_for_campaign,
	preflight_spec,
	run_campaign,
	run_campaign_setup,
	setup_campaign_from_spec,
)
from .reduce import (
	build_reduce_kwargs,
	reduce_from_manifest,
	reduceSEE,
	resolve_ipts_for_run,
)
from .workspace_groups import (
	adopt_into_artefact_group,
	adopt_into_diagnostics_group,
	artefact_group_name,
	diagnostic_group_name,
	finalize_builder_workspaces,
	purge_artefacts_for_run,
	purge_artefacts_for_runs,
)

__all__ = [
	"SlugConflictError",
	"add_candidate_species",
	"annotate_run",
	"append_jsonl_record",
	"ApplicabilityScope",
	"ArtefactDefinition",
	"AssetArtefactExample",
	"AssetApplicability",
	"AssetDefinition",
	"AssetRecord",
	"AssetStatus",
	"AssetType",
	"adopt_into_artefact_group",
	"adopt_into_diagnostics_group",
	"artefact_group_name",
	"auto_register_bin_mask_for_campaign",
	"bootstrap_campaign",
	"bootstrap_campaign_from_manifest",
	"build_crystal_species",
	"build_crystal_species_from_cif",
	"build_crystal_species_from_cif_and_eos",
	"build_example_artefact",
	"build_requirement_report",
	"build_requirement_report_from_seemeta",
	"build_reduce_kwargs",
	"build_run_manifest",
	"build_swiss_cheese_from_run",
	"build_swiss_cheese_from_ub_files",
	"build_swiss_cheese_from_transmission_monitor",
	"copy_artefact",
	"detect_notches_in_spectrum",
	"diagnostic_group_name",
	"EOSObject",
	"finalize_builder_workspaces",
	"generate_requirement_reports_from_campaign_specs",
	"generate_requirement_report_for_run",
	"get_campaign_artefact_dir",
	"get_campaign_paths",
	"get_schema_path",
	"get_requirement_specs",
	"infer_assembly_type_from_run",
	"infer_assembly_type_from_seemeta",
	"ingest_asset",
	"ingest_seemeta_for_run",
	"list_asset_records",
	"list_artefact_records",
	"list_asset_artefact_examples",
	"list_campaigns",
	"list_crystal_species_records",
	"list_schema_paths",
	"load_eos_description",
	"load_phase_description",
	"LoadedAsset",
	"normalize_assembly_type",
	"PixelMaskWorkspaceObject",
	"preflight_campaign_specs_seemeta",
	"preflight_spec",
	"purge_artefacts_for_run",
	"purge_artefacts_for_runs",
	"register_asset_record",
	"register_attenuation_artefact_planned",
	"register_crystal_species_artefact",
	"register_manual_bin_mask_artefact",
	"register_pixel_mask_artefact",
	"register_swiss_cheese_artefact",
	"rename_campaign_slug",
	"retire_artefact",
	"reset_artefacts_index",
	"read_jsonl_records",
	"reduce_from_manifest",
	"reduceSEE",
	"resolve_campaign_slug",
	"resolve_ipts_for_run",
	"run_campaign",
	"run_campaign_setup",
	"setup_campaign_from_spec",
	"SwissCheeseObject",
	"validate_jsonl_file",
	"validate_record",
]
